---
title: "Final Assignment"
author: "Daniel Galea, Konrad Karas and Long Tran, group 6"
date: "21 March 2018"
output: pdf_document
fontsize: 11pt
highlight: tango
---

### Exercise Galapagos

```{r}
galapagos = read.table("gala.txt", header = TRUE)
attach(galapagos)
```

**Point 1**

```{r}
summary(lm(Species ~ Area + Elevation + Nearest + Scruz + Adjacent, data = galapagos))
```


```{r}
summary(lm(Species ~ Area + Elevation + Scruz + Adjacent, data = galapagos))
```

```{r}
summary(lm(Species ~ Elevation + Scruz + Adjacent, data = galapagos))
```

```{r}
summary(lm(Species ~ Elevation + Adjacent, data = galapagos))
```

**Point 2**


```{r}
summary(lm(sqrt(Species) ~ Area + Elevation + Nearest + Scruz + Adjacent, data = galapagos))
```

```{r}
summary(lm(sqrt(Species) ~ Area + Elevation + Scruz + Adjacent, data = galapagos))
```

```{r}
summary(lm(sqrt(Species) ~ Area + Elevation + Adjacent, data = galapagos))
```

```{r}
summary(lm(sqrt(Species) ~ Elevation + Adjacent, data = galapagos))


```

**Point 3**

```{r}
model1 = lm(Species ~ Elevation + Adjacent, data = galapagos)
model2 = lm(sqrt(Species) ~ Elevation + Adjacent, data = galapagos)

par(mfrow = c(1, 2))
qqnorm(residuals(model1))
qqline(residuals(model1))
plot(fitted(model1), residuals(model1))

par(mfrow = c(1, 2))
qqnorm(residuals(model2))
qqline(residuals(model2))
plot(fitted(model2), residuals(model2))
```

**Point 4**

**Point 5**

**Point 6**

**Point 7**

**Point 8**

**Point 9**

**Point 10**

